### PR TITLE
rewrite validation and template rendering

### PR DESCRIPTION
**Pull request by TomasTomecek**
still wip, please don't merge; fix for #46 is still missing

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Coding done! This is super meaty, can someone review please? (CC @mmilata @twaugh @jpopelka)
Once reviewed, I'll improve commit msg and should be ready to merge.
Also, @pbabinca can you try the new type of build please? It's named *prod without koji*.

**Comment by mmilata** [comment]
Sure, I can do it.

**Comment by mmilata** [comment]
Looks good to me!

**Comment by TomasTomecek** [comment]
@mmilata Martin, thanks for review!

@pbabinca here's how you can test it:

set build_type in config to [prod-without-koji](https://github.com/DBuildService/osbs/blob/rewrite-validation/osbs/constants.py#L30):

```
build_type = prod-without-koji
```

There are three ways how you can initiate the build

**1)**
original way should work

```python
osbs.create_build(**kwargs)
```

**2)**
you can directly ask for the specific build type:

```python
osbs.crete_prod_without_koji_build(<specific args>)
```

**3)**
I would prefer this one:

```python
build_request = osbs.osbs_get_build_request()  # return instance of BuildRequest from osbs.build.build_request
build_request.set_params(**kwargs)
osbs.create_build_from_buildrequest(build_request)  # renders the build request and submits the build
```

**Comment by TomasTomecek** [comment]
rebased and I think this is ready to be merged

**Pull request merged**
