### PR TITLE
Make it possible to package post-releases properly. Fixes #91

### LINKED ISSUE #91: Update spec file to create pre-releases
I'd like to test pre-released osbs versions but I need to have it as a rpm package. Please modify spec file to create dev pre-releases (with correct upgrade path between versions).

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
what should we put to `setup.py`?

**Comment by bkabrda** [comment]
`setup.py` doesn't require any change AFAICS... or does it?

**Comment by TomasTomecek** [comment]
aha, so we'll just bump spec and update commit in spec? sounds good to me

**Comment by bkabrda** [comment]
Yeah, exactly.

**Comment by TomasTomecek** [comment]
Thanks Slavek! I'm going to try it right away :)

**Pull request merged**
